'use client'

import React, { useEffect, useContext, useState } from 'react'
import UserContext from '@/context/UserContext'
import { useRouter } from 'next/navigation'
// import Header from './Header'
import Head from 'next/head'
import Spinner from '../elements/Spinner'

interface Page {
  children: React.ReactNode,
  title?: string,
  protect?: boolean
}

const Page = ({ children, title = 'Lesprit', protect }: Page) => {
  const router = useRouter();

  const { currentUser, loading }: any = useContext(UserContext);

  useEffect(() => {
    if (!loading && !currentUser && protect) {
      router.push('/login')
    }
  }, [currentUser, loading]);

  return (
    <div>
      <Head>
        <title>{title}</title>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href=".icons/apple-icon-180.png"></link>
        <meta name="theme-color" content="#FFF" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header authenticated={currentUser} username={currentUser?.name} /> */}

      {protect && !currentUser ? <Spinner /> : children}
    </div>
  )
}

export default Page;