import type { Metadata } from "next";
import { Geist, Geist_Mono, Great_Vibes, Lato } from "next/font/google";
import '@/sass/main.scss'
import StoreProvider from '@/store/StoreProvider';
import { UserContextProvider } from '@/context/UserContext';
import { ReviewContextProvider } from '@/context/ReviewContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: "400",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Lesprit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <UserContextProvider>
          <ReviewContextProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              {children}
            </body>
          </ReviewContextProvider>
        </UserContextProvider>
      </StoreProvider>
    </html>
  );
}
