import '@/sass/main.scss'
import type { Metadata } from "next";
import { Geist, Geist_Mono, Great_Vibes } from "next/font/google"
import StoreProvider from '@/store/StoreProvider'
import { UserContextProvider } from '@/context/UserContext'
import { ReviewContextProvider } from '@/context/ReviewContext'
import localFont from 'next/font/local'
import NextTopLoader from 'nextjs-toploader'
import { ConfigProvider } from 'antd';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: "400",
  subsets: ["latin"],
});


export const mustafa = localFont({
  src: '../assets/fonts/mustafa.woff2',
  display: 'swap',
  variable: '--font-mustafa',
})

const metadata: Metadata = {
  title: "Lesprit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <UserContextProvider>
          <ReviewContextProvider>
            <body className={`antialiased`}>
              <NextTopLoader showSpinner={false} color="#E9BB74" />
              <ConfigProvider
                theme={{
                  token: {
                    colorPrimary: '#FFBC00'
                  }
                }}
              >
                {children}
              </ConfigProvider>
            </body>
          </ReviewContextProvider>
        </UserContextProvider>
      </StoreProvider>
    </html>
  );
}
